# -----------------------------------------------------------
# This conda environment file describes all dependencies the
# underlying code has during build, test, development and
# runtime.
#
# Because creating conda environments is relatively slow we
# have introduced the marker '#othoz:dev' that can be used to
# mark dependencies that are required during local development
# only. Those are automatically filtered out on the CI server
# with the sole purpose of reducing build time.
# -----------------------------------------------------------
name: othoz-paragraph
channels:
  - defaults
  - conda-forge
  - othoz
dependencies:
  # ---------------------------
  # Actual runtime dependencies
  # ---------------------------
  - python~=3.5
  - attrs>=18.1.0  # (attrs follows CalVer) 18.1.0 or higher for attr.ib(factory=f)

  # ------------------------------------------------------------------------
  # Dependencies for running tests, coverage, style and static code analysis
  # ------------------------------------------------------------------------
  - pytest~=4.5
  - pytest-cov~=2.5
  - pytest-sugar~=0.9.2
  - flake8~=3.7
  - codacy-coverage~=1.3
  - pytest-benchmark~=3.2

  # ---------------------------------------------------------
  # Dependencies for building and deploying the documentation
  # ---------------------------------------------------------
  - sphinx~=1.7
  - sphinx_rtd_theme~=0.4.1
  - sphinx-autodoc-typehints~=1.3
  - awscli~=1.16
