package:
  name: othoz-paragraph
  version: {{ environ.get('VERSION', '') }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python ~=3.5
    - attrs >=18.1.0  # (attrs follows CalVer) 18.1.0 or higher for attr.ib(factory=f)

about:
  summary: othoz-paragraph is a micro-framework supporting parallel and lazy evaluation of computation graphs.
